%%% Plot threshold generated by Exp1_mini %%%

%% Key for STDP/Threshold Link (Exp no. and dW no.)
key = [495 613 200 358 619 246 681 750 216 70 334; ...
       32  33  42  43  44  45  46  47  48  49 50];

%% Load dW matrices
% Load average dW matrix
f = dir('~/Desktop/Exp22_mini/');
D = [];
R = [];
for i = 1:numel(f)
    if any(strfind(f(i).name,'Wn')), load([f(i).folder '/' f(i).name]), continue, end
    if ~any(strfind(f(i).name,'.mat')), continue, end
    load([f(i).folder '/' f(i).name])
    assert(d.seizure==1)
    fprintf(['Loading ' f(i).folder '/' f(i).name '...\n'])
    D = cat(3,D,d.dW);
    R = cat(3,R,rot90(d.dW,2));
%     
%     x = ((D(:,:,end)-1).*(Wn>0));
%     
%     X = []; for i = 1:500
%         j = i-50:i+50;
%         X = [X [nan(sum(j<=0),1); x(j(j>0&j<=500),i); nan(sum(j>500),1)]];
%     end
%     
%     F = cat(3,F,full(X).');
end

F = cat(3,D,R);
   
%% Load data
P = {};
ST = {};
DW = {};
for ix = 1:size(key,2)
    f = ['~/Desktop/Exp' num2str(key(2,ix)) '_mini/'];
    if ~exist(f,'dir'), continue, end
    f = dir(f);
    o = []; ii=[];
    for i = 1:numel(f)
        if ~any(strfind(f(i).name,'.mat')), continue, end
        load([f(i).folder '/' f(i).name])
        ixb = strfind(f(i).name,'_'); ixe = strfind(f(i).name,'.mat'); ia = str2num(f(i).name(ixb(end)+1:ixe-1)); %if ia>10, ia=ia./10; end
        ii=[ii ia];
        o = [o [d.seizure].'];
    end
    
    [~,i] = sort(ii);
    o = o(:,i);
    p1 = sum(o)./size(o,1);
    st1 = ii(i);
    P = [P {p1}];
    ST = [ST {st1}];
    DW = [DW {F(:,:,key(1,ix))}];
end

%% Fit threshold data to sigmoid function
Fit = {};
for ix = 1:numel(P)
    sig = @(x) (1 + exp(-(ST{ix}-x(1))./x(2))).^(-1);
    ofn = @(x) sum((sig(x)-P{ix}).^2);
    fit = fminsearch(ofn,[1.5,1]);
    Fit = [Fit {fit; sig}];
end
thresh = cellfun(@(f)f(1),Fit(1,:));

%% Plot
f = figure; hold on
a = gca;
for ix = 1:numel(P)
    plot(ST{ix},P{ix},'o','MarkerSize',6)
    a.Children(1).MarkerFaceColor = a.Children(1).Color;
    a.Children(1).MarkerEdgeColor = 'k';
    plot(ST{ix},Fit{2,ix}(Fit{1,ix}),'LineWidth',2,'Color',[a.Children(1).MarkerFaceColor 0.25])
end

%% Make graph
% p is a matrix gathered from simulations with size 1 x numel(stim_durations)
% above; it has in each element the probability of seizure
if exist('h','var') && isvalid(h) && isa(h,'matlab.ui.Figure'), h = gcf; else h = figure(); end
if ~exist('cl','var'), cl = get(gca,'ColorOrder'); xi = 1; end
a = gca;
hold on
plot(st1,p1,'o','MarkerEdgeColor','k','MarkerFaceColor',cl(xi,:),'MarkerSize',6); 
% plot(st1,p1,'o','MarkerSize',14);
plot(st1,sig(fit),'LineWidth',2,'Color',[cl(xi,:) 0.25]);
xi = xi+1;
a.Title.String = 'Probability of seizure';
% a.XLabel.String = 'Stimulation duration (s)';
a.XLabel.String = '\sigma_{S} (noise level, pA)';
a.YLabel.String = 'Probability';
a.FontSize = 18;
% a.XLim = [2 4];
a.YLim = [0 1];
legend({'p(seizure)','Sigmoid fit'},'Location','NorthWest')
figname = 'pseizure';
% saveas(f,['~/Desktop/' figname '.svg'])
% close(f)
