%%% Plot threshold generated by Exp1_mini %%%

%% Load data
f = dir('~/Desktop/Exp5_mini/');
o = []; ii=[];
for i = 1:numel(f)
    if strcmp(f(i).name,'.') || strcmp(f(i).name,'..') || any(strfind(f(i).name,'.DS_Store')) || any(strfind(f(i).name,'.txt')) || any(strfind(f(i).name,'_traces'))
        continue
    end
    load([f(i).folder '/' f(i).name])
    ixb = strfind(f(i).name,'_'); ixe = strfind(f(i).name,'.mat'); ia = str2num(f(i).name(ixb(end)+1:ixe-1)); if ia>10, ia=ia./10; end
    ii=[ii ia];
    o = [o [d.seizure].'];
end

[~,i] = sort(ii);
o = o(:,i);
p1 = sum(o)./size(o,1);
st1 = ii(i);

%% Fit threshold data to sigmoid function
sig = @(x) (1 + exp(-(st1-x(1))./x(2))).^(-1);
ofn = @(x) sum((sig(x)-p1).^2);
fit = fminsearch(ofn,[1.5,1]);

%% Make graph
% p is a matrix gathered from simulations with size 1 x numel(stim_durations)
% above; it has in each element the probability of seizure
f = figure();
hold on
plot(st1,p1,'.','MarkerSize',14); 
% plot(st1,p1,'o','MarkerSize',14);
plot(st1,sig(fit),'LineWidth',2);
a = gca;
a.Title.String = 'Probability of seizure';
a.XLabel.String = 'Stimulation duration (s)';
a.YLabel.String = 'Probability';
a.FontSize = 18;
% a.XLim = [2 4];
a.YLim = [0 1];
legend({'p(seizure)','Sigmoid fit'},'Location','NorthWest')
figname = 'pseizure';
% saveas(f,['~/Desktop/' figname '.svg'])
% close(f)
