%% Determine threshold of updated (mini) model (i.e. after one round of STDP)
%% Load data from PlasticityExperiment
% PlasticityExperiment directory

% Updated variable directory for PlasticityExperiments
PlasticityVarDir = 'PlasticityExperiment';
% Directory for specific experiment
PlasticityExpName = 'naive';
% Generate container for PlasticityExperiment

% Create/update PlasticityExperiment
PE = PlasticityExperiment(PlasticityExpName);
PE.UpdateDir(PlasticityVarDir);
% Load PlasticityExperiment

% Load PlasticityExperiment
Load(PE)
% Parse PlasticityExperiment

% Parsing runs PCA on data to produce appropriate PCA-space coordinates
Parse(PE)
%% List of 100 updated weigthing matrices generated by PlasticityExperiment naive.mlx

% Select 100 of the matrices generated by PlasticityExperiment naive.mlx
key = [ 4    32    53    95   130   146   166   186   208   218   250   270   288   306   332   365   404   426   440   480
       18    34    65    98   132   153   167   188   209   220   261   272   293   310   337   366   409   428   447   482
       20    43    81   101   135   158   168   198   211   221   262   274   299   312   342   373   417   433   452   490
       21    47    87   119   136   160   173   204   213   223   264   279   301   323   352   381   420   434   457   493
       24    51    94   125   142   161   179   205   215   229   266   283   305   324   354   402   422   436   463   495];

%% Cycle through ThresholdExperiments for weighting matrices given in key

for i = 1:numel(key)

    % Choose particular weighting matrix from key
    n = key(i);

    %%% ThresholdExperiment preliminaries
    % Directories for saving
    VarDir = 'ThresholdExperiment/STDP'; % Updated variable directory for ThresholdExperiments
    
    % Directory for specific experiment
    ExpName = sprintf([PlasticityVarDir '-' PlasticityExpName '-%d'],n);

    % Generate container for ThresholdExperiment
    E = ThresholdExperiment(ExpName); % Create/update ThresholdExperiment
    E.UpdateDir(VarDir);

    % Update ThresholdExperiment settings
    E.param.inputs.levels = 5:2.5:20; % Adjust tested input levels as desired

    %%% Simulation preliminaries
    % Generate container for Simulation
    S = Simulation('DefaultSimulationParameters');

    % Retrieve updated weighting matrix from PlasticityExperiment
    S.param.dW = PE.Retrieve(n);

    % Prepare Simulation
    Prepare(S);

    % Link ThresholdExperiment to Simulation
    E.S = S;
    
    %%% Run ThresholdExperiment
    Run(E)

end